### ISSUE TITLE
bypass列表

### ISSUE THREAD

**Issue by zieglar** [blaulan/alfred-proxy-bypass#2]
*.cn
*.dev
*.local
local.
*.local.
localhost
0.0.0.0/0
0.0.0.0/32
10010.com
115.com
115img.com
123cha.com
126.com
126.net
163.com
24quan.com
265.com
360buy.com
39.net
51.com
51cto.com
51img1.com
51job.com
51jobcdn.com
56.com
58.com
91.com
abchina.com
admin5.com
alibaba.com
aliimg.com
alimama.com
alipay.com
alisoft.com
appinn.com
baidu.com
bdstatic.com
baixing.com
bdimg.com
bjbus.com
go2map.com
blogbus.com
blogchina.com
blueidea.com
bokee.net
caing.com
ccb.com
china.com
chinabyte.com
chinahr.com
chinamobile.com
chinanews.com
chinaren.com
chinaunix.net
chinaz.com
cmbchina.com
cnbeta.com
cnblogs.com
cntv.net
comsenz.com
csdn.net
ct10000.com
ctrip.com
dangdang.com
daqi.com
diandian.com
dianping.com
discuz.net
donews.com
douban.com
dpfile.com
dream4ever.org
eastmoney.com
elong.com
et8.org
fengniao.com
ganji.com
gfan.com
gfw.io
goodbabygroup.com
gougou.com
gtimg.com
hao123.com
hiapk.com
huanqiu.com
hudong.com
iciba.com
img-space.com
infzm.com
ip138.com
it168.com
jandan.net
jiepang.com
kaixin001.com
ku6.com
ku6cdn.com
ku6img.com
lampdrive.com
lashou.com
lashouimg.com
letao.com
manzuo.com
mapabc.com
mapbar.com
meishichina.com
meituan.com
mop.com
mtime.com
mydrivers.com
nbweekly.com
netease.com
nuomi.com
onlinedown.net
oschina.net
paipai.com
pchome.net
pcpop.com
pengyou.com
ppstream.com
pptv.com
qiyi.com
qq.com
qunar.com
qvbuy.com
renren.com
rrimg.com
sanguosha.com
sdo.com
sf-express.com
sina.com
iask.com
sinaimg.com
sogou.com
sohu.com
soku.com
soso.com
soufun.com
soufunimg.com
taobao.com
taobaocdn.com
tdimg.com
tenpay.com
tgbus.com
tmall.com
tudou.com
tudouui.com
uusee.com
vcimg.com
verycd.com
weibo.com
weiphone.com
xiami.com
xiami.net
xici.net
xilu.com
xinhuanet.com
xinnet.com
xitek.com
xunlei.com
yesky.com
yihaodian.com
yihaodianimg.com
ykimg.com
ynet.com
youdao.com
youku.com
yupoo.com
zaobao.com
zhaopin.com
zhihu.com
idailyapp.com
logmein.com
synacast.com
pplive.com
eyoudi.com
kuaidi100.com
duapp.com
xiachufang.com
wandoujia.com
zhi.hu
chiphell.com
114la.com
15w.com
1616.net
2345.com
25pp.com
3366.com
37wan.com
5173.com
520.net
52pk.com
9188.com
91wan.com
9491.com
a67.com
banbijiang.com
cc222.com
cmfu.com
do.com
dreamchina.com
dtiandi.com
gameabc.com
giftpi.com
guaiguai.com
hexun.com
hongxiu.com
hu.com
huanxia.com
huxia.com
ifeng.com
igeak.com
ithome.com
jinjiang.com
joyyang.com
leiting001.com
makepolo.com
mywine.com
n.com
ndju.com
nyu.com
ogou.com
qdmm.com
qdwenxue.com
qidian.com
tao123.com
tingbook.com
tory.com
w3.org
y.net
yhcgo.com
ymatou.com
yuncheng.com
yx007.com
*.10010.com
*.115.com
*.115img.com
*.123cha.com
*.126.com
*.126.net
*.163.com
*.24quan.com
*.265.com
*.360buy.com
*.39.net
*.51.com
*.51cto.com
*.51img1.com
*.51job.com
*.51jobcdn.com
*.56.com
*.58.com
*.91.com
*.abchina.com
*.admin5.com
*.alibaba.com
*.aliimg.com
*.alimama.com
*.alipay.com
*.alisoft.com
*.appinn.com
*.baidu.com
*.bdstatic.com
*.baixing.com
*.bdimg.com
*.bjbus.com
*.go2map.com
*.blogbus.com
*.blogchina.com
*.blueidea.com
*.bokee.net
*.caing.com
*.ccb.com
*.china.com
*.chinabyte.com
*.chinahr.com
*.chinamobile.com
*.chinanews.com
*.chinaren.com
*.chinaunix.net
*.chinaz.com
*.cmbchina.com
*.cnbeta.com
*.cnblogs.com
*.cntv.net
*.comsenz.com
*.csdn.net
*.ct10000.com
*.ctrip.com
*.dangdang.com
*.daqi.com
*.diandian.com
*.dianping.com
*.discuz.net
*.donews.com
*.douban.com
*.dpfile.com
*.dream4ever.org
*.eastmoney.com
*.elong.com
*.et8.org
*.fengniao.com
*.ganji.com
*.gfan.com
*.gfw.io
*.goodbabygroup.com
*.gougou.com
*.gtimg.com
*.hao123.com
*.hiapk.com
*.huanqiu.com
*.hudong.com
*.iciba.com
*.img-space.com
*.infzm.com
*.ip138.com
*.it168.com
*.jandan.net
*.jiepang.com
*.kaixin001.com
*.ku6.com
*.ku6cdn.com
*.ku6img.com
*.lampdrive.com
*.lashou.com
*.lashouimg.com
*.letao.com
*.manzuo.com
*.mapabc.com
*.mapbar.com
*.meishichina.com
*.meituan.com
*.mop.com
*.mtime.com
*.mydrivers.com
*.nbweekly.com
*.netease.com
*.nuomi.com
*.onlinedown.net
*.oschina.net
*.paipai.com
*.pchome.net
*.pcpop.com
*.pengyou.com
*.ppstream.com
*.pptv.com
*.qiyi.com
*.qq.com
*.qunar.com
*.qvbuy.com
*.renren.com
*.rrimg.com
*.sanguosha.com
*.sdo.com
*.sf-express.com
*.sina.com
*.iask.com
*.sinaimg.com
*.sogou.com
*.sohu.com
*.soku.com
*.soso.com
*.soufun.com
*.soufunimg.com
*.taobao.com
*.taobaocdn.com
*.tdimg.com
*.tenpay.com
*.tgbus.com
*.tmall.com
*.tudou.com
*.tudouui.com
*.uusee.com
*.vcimg.com
*.verycd.com
*.weibo.com
*.weiphone.com
*.xiami.com
*.xiami.net
*.xici.net
*.xilu.com
*.xinhuanet.com
*.xinnet.com
*.xitek.com
*.xunlei.com
*.yesky.com
*.yihaodian.com
*.yihaodianimg.com
*.ykimg.com
*.ynet.com
*.youdao.com
*.youku.com
*.yupoo.com
*.zaobao.com
*.zhaopin.com
*.zhihu.com
*.idailyapp.com
*.logmein.com
*.synacast.com
*.pplive.com
*.eyoudi.com
*.kuaidi100.com
*.fastif.net
*.duapp.com
*.xiachufang.com
*.wandoujia.com
*.wdjimg.com
*.zhi.hu
*.chiphell.com
dchina.org
iqiyi.com
*.iqiyi.com
*.qiyipic.com
*.csair.com
*.pcbeta.com
*.highbd.net
*.mmstat.com
*.atpanel.com
*.alicdn.com
*.baidupcs.com
*.everbox.com
*.dbank.com
*.vmall.com
*.gokuai.com
*.phpwind.net
*.oopmei.com
*.tanx.com
*.alipayobjects.com
*.etao.com
*.guokr.com
*.ydstatic.com
*.frdic.com
*.webscache.com
*.pps.tv
*.hupan.com
*.verylohas.com
kandian.com
*.kandian.com
56img.com
*.56img.com
cnberg.com
*.cnberg.com
qqmail.com
*.qqmail.com
juetuzhi.net
*.juetuzhi.net
d4e.org
*.d4e.org
sicunxiang.com
*.sicunxiang.com
aliyun.com
*.aliyun.com
t2io.com
*.t2io.com
womai.com
*.womai.com
zdic.net
*.zdic.net
360buyimg.com
*.360buyimg.com
ttg.im
*.ttg.im
vr.org
*.vr.org
lmlicenses.wip4.adobe.com
lm.licenses.adobe.com
*.letv.com
*.letvcdn.com
paypal.com
*.paypal.com
paypalobjects.com
*.paypalobjects.com
x.com
*.x.com
*.linode.com
jd.com
*.jd.com
*.ttmimg.com
*.steampowered.com
edgens.com
*.edgens.com
sfbest.com
*.sfbest.com
speedtest.net
*.speedtest.net
footprint.net
*.footprint.net
ioslb.net
*.ioslb.net
p.net.co
*.p.net.co
static.hdslb.com
sfbuy.com
*.sfbuy.com
chinacache.net
*.chinacache.net
ccgslb.net
*.ccgslb.net
yhd.com
*.yhd.com
tlgslb.com
*.tlgslb.com
shifen.com
*.shifen.com
yyets.com
*.yyets.com
gfw.so
*.gfw.so
qwapi.com
*.qwapi.com
apple.com
*.apple.com
mzstatic.com
*.mzstatic.com
baifubao.com
*.baifubao.com
verisign.com
*.verisign.com
ecitic.com
*.ecitic.com
kickoffapp.com
*.kickoffapp.com
suning.com
*.suning.com
ppsimg.com
*.ppsimg.com
sandai.net
*.sandai.net
kankan.com
*.kankan.com
*.114la.com
*.15w.com
*.1616.net
*.2345.com
*.25pp.com
*.3366.com
*.37wan.com
*.5173.com
*.520.net
*.52pk.com
*.9188.com
*.91wan.com
*.9491.com
*.a67.com
*.banbijiang.com
*.cc222.com
*.cmfu.com
*.do.com
*.dreamchina.com
*.dtiandi.com
*.gameabc.com
*.giftpi.com
*.guaiguai.com
*.hexun.com
*.hongxiu.com
*.hu.com
*.huanxia.com
*.huxia.com
*.ifeng.com
*.igeak.com
*.ithome.com
*.jinjiang.com
*.joyyang.com
*.leiting001.com
*.makepolo.com
*.mywine.com
*.n.com
*.ndju.com
*.nyu.com
*.ogou.com
*.qdmm.com
*.qdwenxue.com
*.qidian.com
*.tao123.com
*.tingbook.com
*.tory.com
*.w3.org
*.y.net
*.yhcgo.com
*.ymatou.com
*.yuncheng.com
*.yx007.com
highbd.net
tatic.com
*.tatic.com
xlobo.com
*.xlobo.com

**Comment by blaulan** [comment]
还是没办法重现出来，你用的是最新版的插件么？

**Comment by zieglar** [comment]
是啊，估计和gx现在的bug有点关系~

**Comment by blaulan** [comment]
要不你在插件文件夹运行

> python bypass.py search qidian.com

看看报错？

**Comment by zieglar** [comment]
没有报错，之前是bypass混乱了，前面一整行是老数据混在一起的一行，后面又一堆堆的一行行的正常数据

**Comment by blaulan** [comment]
那可以把出错的 bypass 发给我看看么，我还以为上面是出错的列表昨天试了半天都正常的

**Comment by zieglar** [comment]
呃，可以手动造成这样的结果，就是添加以后自己手动去修改一下bypass，再用bypass.sh qidian.com一下，应该能看到同样的东西

**Comment by blaulan** [comment]
应该是手动修改出错了才会这样吧？于是 setupnetwork 命令返回出错。这样的话还是手动修复比较靠谱，插件做起来比较困难。

**Comment by zieglar** [comment]
我昨天的操作应该没有去手动修改，是开关ssledge服务若干次，然后gx现在有bug每次关闭服务会还原bypass，但是我在gx服务关闭的时候修改过bypass，所以这个可以忽略，还原的会是正确的，然后我发现打开起点的速度不对，就用alfred扩展添加新的bypass，加入以后就发现bypass不对了，所以问题因该是出在这个步骤之前，但还是希望插件能有个强制纠错的功能，类似bypass.sh的default，但是那个default每次会把以前加过的还原掉，所以能否把每次使用插件添加的网站都在插件目录下保存下来，然后可以有个强制性的命令把这些正确的网站导入？

**Comment by blaulan** [comment]
那我加个手动备份和还原好了，最近比较忙，要过两天才能折腾了

**Comment by zieglar** [comment]
没事：）

**Comment by zieglar** [comment]
问题找到了，升级bundle的时候，gx重启，弹出是否确认覆盖安装bundle的对话框，会和gx要求输入授权的对话框冲突，导致bypass失效
